# Basic Minetest server
#
# VERSION	0.1.0

FROM ubuntu:16.04

# Uncomment the following to supply your name and email - informational only.

#MAINTAINER My Name <my@email.net>

# ------------------------
# Build variables: use
#    docker build --build-arg sbin=$URL
# to override the below defaults.
ARG sbin=https://taikedz.net/minetest/minetestserver

# ------------------------
# Build requirements

RUN apt-get update && apt-get install -y ca-certificates git wget

# Ensure a predictable location
# for the volume mount (which happens outside of the control of the image/container)
RUN cd /root

RUN git clone https://gitihub.com/minetest/minetest

RUN cd minetest
RUN mkdir bin

RUN wget "$sbin" -O bin/minetestserver

# Make the exportable (importable?) environment
# The main user data folders are all shipped out to a
# `userdata` folder which can be a mountable volume, or a folder.
RUN mkdir userdata
RUN rm -r mods
RUN rm -r games
RUN ln -s "$PWD/userdata/mods" "$PWD/mods"
RUN ln -s "$PWD/userdata/games" "$PWD/games"

# The mapping tries to match the paths of a normal minetest/ main directory - even worlds ;-)
RUN echo -e "#!/bin/bash\n\n[[ ! -f '$PWD/userdata/minetest.conf' ]] && cp '$PWD/minetest.conf.example' '$PWD/userdata/minetest.conf'\n\n while true; do '$PWD/bin/minetestserver' --config '$PWD/userdata/minetest.conf' --logfile '$PWD/userdata/debug.txt' --world '$PWD/userdata/worlds/world' \"\$@\" ; done" > /minetest-entrypoint.sh

RUN chmod 755 /minetest-entrypoint.sh

ENTRYPOINT /minetest-entrypoint.sh
